custom_exception: change init signature to accept anyerror
Instead of custom exception ErrorSet.
Indeed at comptime we do not know the error type and therefore
we can not pass the ErrorSet if we want to handle a superset in
the returned error union of the function.

Signed-off-by: Francis Bouvier <francis@lightpanda.io>